version: '2.3'
services:
  nb_suizo:
    runtime: nvidia
    build:
      context: ./
    image: chenaoki/nb_basic
    container_name: tomii_suizo
    ports:
      - "5438:8888"
    volumes:
      - ./:/notebooks
      - /mnt:/mnt

